GET http://localhost:3000/

###

GET http://localhost:3000/bye

###

GET http://localhost:3000/hello
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhaWZ1bCIsInBhc3N3b3JkIjoiMDEyMzQ1IiwibmFtZSI6IlNhaWZ1bCBBenJlZSBCaW4gU2FpZnVsIEF6bWkiLCJlbWFpbCI6ImF6cmVlYXlpZTI0QGdtYWlsLmNvbSIsImlhdCI6MTY4MTExMTY1MCwiZXhwIjoxNjgxMTE1MjUwfQ.b5QxQBS0vlYE8T7TLEuJYy13XGSKJP9Um-dLQ4QuKh8

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "saiful",
    "password": "012345"
}

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "daus",
    "password": "000000",
    "name": "Firdaus Hassan",
    "email": "firdaus@gmail.com"
}