GET http://localhost:3000/

###

GET http://localhost:3000/bye

###

GET http://localhost:3000/hello
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhdXMiLCJwYXNzd29yZCI6IjAwMDAwMCIsIm5hbWUiOiJGaXJkYXVzIEhhc3NhbiIsImVtYWlsIjoiZmlyZGF1c0BnbWFpbC5jb20iLCJpYXQiOjE2ODE2NjEwNzEsImV4cCI6MTY4MTY2NDY3MX0.D8RwW_2KFkCcb-eIwdUe3NQJDVihDqLDVntt9m_Hi-E

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "daus",
    "password": "000000"
}

###

POST http://localhost:3000/login2
Content-Type: application/json

{
    "username": "saiful",
    "password": "012345"
}

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "daus",
    "password": "000000",
    "name": "Firdaus Hassan",
    "email": "firdaus@gmail.com"
}